name: msvc-dev-cmd

on:
  pull_request:
  push:
    branches:
      - master
      - release/*
      - new-windows
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    name: default
    runs-on: ${{ matrix.windows }}
    strategy:
      matrix:
        windows: [windows-2016, windows-2019]
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: z5-build-env
          auto-update-conda: true
          channels: conda-forge
          environment-file: .github/workflows/environment.yaml
          python-version: 3.7
          auto-activate-base: false
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Download Internet
        run: npm install
      - name: Enable Developer Command Prompt
        uses: ./
      - name: Compile and run some C code
        shell: cmd
        run: |
          cl.exe hello.c
          hello.exe
  audit:
    name: npm audit
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - run: npm install
      - run: npm audit --audit-level=moderate
  alias-arch:
    name: arch aliases
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Download Internet
        run: npm install
      - name: Enable Developer Command Prompt
        uses: ./
        with:
          arch: Win32
      - name: Compile and run some C code
        shell: cmd
        run: |
          cl.exe hello.c
          hello.exe
